name: shohdotdev_template
description: "Flutter template projects by shoh.dev"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Data
  fpdart: ^1.1.0
  get_it: ^7.7.0
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.3

  #  Network
  dio: ^5.5.0+1

  # Database
  supabase_flutter: ^2.5.7

  # Routing
  go_router: ^14.2.0

  # UI
  cupertino_icons: ^1.0.6
  bot_toast: ^4.1.3
  nil: ^1.1.1

  # Etc
  slang: ^3.31.1
  fl_location: ^3.1.0
  mocktail: ^1.0.4
  js: ^0.7.1
  flutter_hooks: ^0.20.5
  async_redux: ^23.1.1
  provider_for_redux:
    path: ./provider_for_redux/
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
