// Mocks generated by Mockito 5.4.4 from annotations
// in shohdotdev_template/test/core/env/env_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_dotenv/flutter_dotenv.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:shohdotdev_template/core/env/env.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDotEnv_0 extends _i1.SmartFake implements _i2.DotEnv {
  _FakeDotEnv_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Env].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnv extends _i1.Mock implements _i3.Env {
  @override
  _i2.DotEnv get env => (super.noSuchMethod(
        Invocation.getter(#env),
        returnValue: _FakeDotEnv_0(
          this,
          Invocation.getter(#env),
        ),
        returnValueForMissingStub: _FakeDotEnv_0(
          this,
          Invocation.getter(#env),
        ),
      ) as _i2.DotEnv);

  @override
  String get apiBaseUrl => (super.noSuchMethod(
        Invocation.getter(#apiBaseUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#apiBaseUrl),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#apiBaseUrl),
        ),
      ) as String);

  @override
  String get supabaseUrl => (super.noSuchMethod(
        Invocation.getter(#supabaseUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#supabaseUrl),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#supabaseUrl),
        ),
      ) as String);

  @override
  String get supabaseAnonKey => (super.noSuchMethod(
        Invocation.getter(#supabaseAnonKey),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#supabaseAnonKey),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#supabaseAnonKey),
        ),
      ) as String);

  @override
  _i5.Future<void> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
